openapi: 3.0.3
info:
  title: Offer resources
  version: '1.0'
paths: {}
components:
  schemas:
    OfferListRequest:
      type: object

      properties:
        limit:
          type: number
          example: 60

    OfferListResponse:
      type: array

      items:
        type: object

        properties:
          id:
            type: string
            example: 66702963a5eed9f50a7a72d5

          title:
            type: string
            example: Супер тестовое предложение

          postDate:
            type: string
            format: date-time
            example: 2024-06-17T12:17:39.905Z

          city:
            $ref: './city.resources.yml#/components/schemas/CityObject'

          preview:
            type: string
            example: https://www.youtube.com/watch?v=dQw4w9WgXcQ

          isPremium:
            type: boolean
            example: true

          isFavorite:
            type: boolean
            example: true

          rating:
            type: number
            example: 5

          housing:
            type: string
            example: apartment
            enum:
              - apartment
              - room
              - house
              - hotel

          rentCost:
            type: number
            example: 50000

          commentsCount:
            type: number
            example: 7

    CreateOfferRequest:
      type: object

      properties:
        title:
          type: string
          example: Супер тестовое предложение

        description:
          type: string
          example: Это крутое предлжения явно не оставит тебя равнодушным

        city:
          type: string
          example: Paris
          enum:
            - Paris
            - Cologne
            - Brussels
            - Amsterdam
            - Hamburg
            - Dusseldorf

        preview:
          type: string
          example: https://www.youtube.com/watch?v=dQw4w9WgXcQ

        photoes:
          type: array
          items:
            type: string
          example: ['path/to/photo1', 'path/to/photo2']

        isPremium:
          type: boolean
          example: true

        housing:
          type: string
          example: apartment
          enum:
            - apartment
            - room
            - house
            - hotel

        roomQuantity:
          type: number
          example: 7

        guestQuantity:
          type: number
          example: 4

        rentCost:
          type: number
          example: 60000

        comforts:
          type: array
          items:
            type: string
          example: ['Breakfast', 'Laptop friendly workspace', 'Fridge']

    CreateOfferResponse:
      type: object

      properties:
        id:
          type: string
          example: 66702963a5eed9f50a7a72d5

        title:
          type: string
          example: Супер тестовое предложение

        postDate:
          type: string
          format: date-time
          example: 2024-06-17T12:17:39.905Z

        city:
          $ref: './city.resources.yml#/components/schemas/CityObject'

        preview:
          type: string
          example: https://www.youtube.com/watch?v=dQw4w9WgXcQ

        isPremium:
          type: boolean
          example: true

        isFavorite:
          type: boolean
          example: true

        rating:
          type: number
          example: 5

        housing:
          type: string
          example: apartment
          enum:
            - apartment
            - room
            - house
            - hotel

        rentCost:
          type: number
          example: 50000

        commentsCount:
          type: number
          example: 7

    OfferDetailResponse:
      type: object

      properties:
        id:
          type: string
          example: 66702963a5eed9f50a7a72d5

        title:
          type: string
          example: Супер тестовое предложение

        description:
          type: string
          example: Супер тестовое предложение описание

        photoes:
          type: array
          items:
            type: string
          example: ['path/to/photo1', 'path/to/photo2']

        roomQuantity:
          type: number
          example: 7

        guestQuantity:
          type: number
          example: 4

        comforts:
          type: array
          items:
            type: string
          example: ['Breakfast', 'Laptop friendly workspace', 'Fridge']

        postDate:
          type: string
          format: date-time
          example: 2024-06-17T12:17:39.905Z

        city:
          $ref: './city.resources.yml#/components/schemas/CityObject'

        user:
          $ref: './user.resources.yml#/components/schemas/UserResponse'

        preview:
          type: string
          example: https://www.youtube.com/watch?v=dQw4w9WgXcQ

        isPremium:
          type: boolean
          example: true

        isFavorite:
          type: boolean
          example: true

        rating:
          type: number
          example: 5

        housing:
          type: string
          example: apartment
          enum:
            - apartment
            - room
            - house
            - hotel

        rentCost:
          type: number
          example: 50000

        commentsCount:
          type: number
          example: 7

    ToggleOfferFavRequest:
      type: object

      properties:
        isFavorite:
          type: boolean
          example: true

        offerId:
          type: string
          example: 667033d31297a7a5d85f7445

    ToggleOfferFavResponse:
      type: object

      properties:
        id:
          type: string
          example: 66702963a5eed9f50a7a72d5

        title:
          type: string
          example: Супер тестовое предложение

        description:
          type: string
          example: Супер тестовое предложение описание

        photoes:
          type: array
          items:
            type: string
          example: ['path/to/photo1', 'path/to/photo2']

        roomQuantity:
          type: number
          example: 7

        guestQuantity:
          type: number
          example: 4

        comforts:
          type: array
          items:
            type: string
          example: ['Breakfast', 'Laptop friendly workspace', 'Fridge']

        postDate:
          type: string
          format: date-time
          example: 2024-06-17T12:17:39.905Z

        city:
          $ref: './city.resources.yml#/components/schemas/CityObject'

        user:
          $ref: './user.resources.yml#/components/schemas/UserResponse'

        preview:
          type: string
          example: https://www.youtube.com/watch?v=dQw4w9WgXcQ

        isPremium:
          type: boolean
          example: true

        isFavorite:
          type: boolean
          example: true

        rating:
          type: number
          example: 5

        housing:
          type: string
          example: apartment
          enum:
            - apartment
            - room
            - house
            - hotel

        rentCost:
          type: number
          example: 50000

        commentsCount:
          type: number
          example: 7

    FavListResponse:
      type: array

      items:
        type: object

        properties:
          id:
            type: string
            example: 66702963a5eed9f50a7a72d5

          title:
            type: string
            example: Супер тестовое предложение

          postDate:
            type: string
            format: date-time
            example: 2024-06-17T12:17:39.905Z

          city:
            $ref: './city.resources.yml#/components/schemas/CityObject'

          preview:
            type: string
            example: https://www.youtube.com/watch?v=dQw4w9WgXcQ

          isPremium:
            type: boolean
            example: true

          isFavorite:
            type: boolean
            example: true

          rating:
            type: number
            example: 5

          housing:
            type: string
            example: apartment
            enum:
              - apartment
              - room
              - house
              - hotel

          rentCost:
            type: number
            example: 50000

          commentsCount:
            type: number
            example: 7

    PremListRequest:
      type: object

      properties:
        city:
          type: string
          example: Paris
          enum:
            - Paris
            - Cologne
            - Brussels
            - Amsterdam
            - Hamburg
            - Dusseldorf

    PremListResponse:
      type: array

      items:
        type: object

        properties:
          id:
            type: string
            example: 66702963a5eed9f50a7a72d5

          title:
            type: string
            example: Супер тестовое предложение

          postDate:
            type: string
            format: date-time
            example: 2024-06-17T12:17:39.905Z

          city:
            $ref: './city.resources.yml#/components/schemas/CityObject'

          preview:
            type: string
            example: https://www.youtube.com/watch?v=dQw4w9WgXcQ

          isPremium:
            type: boolean
            example: true

          isFavorite:
            type: boolean
            example: true

          rating:
            type: number
            example: 5

          housing:
            type: string
            example: apartment
            enum:
              - apartment
              - room
              - house
              - hotel

          rentCost:
            type: number
            example: 50000

          commentsCount:
            type: number
            example: 7
