# Пользователь
## Создать пользователя

POST http://localhost:1337/users/register HTTP/1.1
Content-Type: application/json

{
   "name": "Джон Уик",
   "email": "john@continental.com",
   "password": "9isdrjf90usd",
   "type": "pro"
}

###

## Авторизироваться

POST http://localhost:1337/users/login HTTP/1.1
Content-Type: application/json

{
   "email": "john@continental.com",
   "password": "9isdrjf90usd"
}

###

## Проверить токен пользователя
GET http://localhost:1337/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG5AY29udGluZW50YWwuY29tIiwibmFtZSI6ItCU0LbQvtC9INCj0LjQuiIsImlkIjoiNjY2OGQ3MDU1NGQyNzYzOTlhODIxNGE2IiwiaWF0IjoxNzE4MTQ2ODI5LCJleHAiOjE3MTgzMTk2Mjl9.jrmOI5q4eenrvJi7uQOm2y_oAfOoQ97hMzD7IkT9U3o

###

## Загрузить аватар

POST http://localhost:1337/users/6643e34f81c7dfc04882c0cd/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< C:\Path\To\Image
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
