# Предложения

## Создать предложение

POST http://localhost:1337/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG53aWNrQGdtYWlsLmNvbSIsIm5hbWUiOiJKb2huIFdpY2siLCJpZCI6IjY2NjhlZTczOWMwY2Q5YTYwMzYyY2I4NCIsImlhdCI6MTcxODE1NTE5MywiZXhwIjoxNzE4MzI3OTkzfQ.P0ReVWSz92glvopsXR93JLZNwJQ8FjPuXdrxkQk2Pck

{
  "title": "Супер тестовое предложение",
  "description": "Супер тестовое предложение описание",
  "city": "Paris",
  "preview": "preview.jpg",
  "photoes": ["preview1.jpg", "preview2.jpg", "preview2.jpg", "preview3.jpg"],
  "isPremium": true,
  "housing": "apartment",
  "roomQuantity": 4,
  "guestQuantity": 5,
  "rentCost": 60000,
  "comforts": ["Breakfast", "Laptop friendly workspace"]
}

###

## Получить список предложений

GET http://localhost:1337/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG53aWNrQGdtYWlsLmNvbSIsIm5hbWUiOiJKb2huIFdpY2siLCJpZCI6IjY2NjhlZTczOWMwY2Q5YTYwMzYyY2I4NCIsImlhdCI6MTcxODE1NTE5MywiZXhwIjoxNzE4MzI3OTkzfQ.P0ReVWSz92glvopsXR93JLZNwJQ8FjPuXdrxkQk2Pck

###

## Получить список премиальных предложений

GET http://localhost:1337/offers/premiums?city=Paris HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG53aWNrQGdtYWlsLmNvbSIsIm5hbWUiOiJKb2huIFdpY2siLCJpZCI6IjY2NjhlZTczOWMwY2Q5YTYwMzYyY2I4NCIsImlhdCI6MTcxODE1NTE5MywiZXhwIjoxNzE4MzI3OTkzfQ.P0ReVWSz92glvopsXR93JLZNwJQ8FjPuXdrxkQk2Pck

###

## Переключить состояние 'Избранное'

POST http://localhost:1337/offers/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG53aWNrQGdtYWlsLmNvbSIsIm5hbWUiOiJKb2huIFdpY2siLCJpZCI6IjY2NjhlZTczOWMwY2Q5YTYwMzYyY2I4NCIsImlhdCI6MTcxODE1NTE5MywiZXhwIjoxNzE4MzI3OTkzfQ.P0ReVWSz92glvopsXR93JLZNwJQ8FjPuXdrxkQk2Pck

{
  "isFavorite": true,
  "offerId": "6668d7b84dd596d36a2104ad"
}

###

## Получить список избранных предложений

GET http://localhost:1337/offers/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG53aWNrQGdtYWlsLmNvbSIsIm5hbWUiOiJKb2huIFdpY2siLCJpZCI6IjY2NjhlZTczOWMwY2Q5YTYwMzYyY2I4NCIsImlhdCI6MTcxODE1NTE5MywiZXhwIjoxNzE4MzI3OTkzfQ.P0ReVWSz92glvopsXR93JLZNwJQ8FjPuXdrxkQk2Pck

###

## Получить всю информацию о предложении

GET  http://localhost:1337/offers/6668f54944d73c2074d451d7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG53aWNrQGdtYWlsLmNvbSIsIm5hbWUiOiJKb2huIFdpY2siLCJpZCI6IjY2NjhlZTczOWMwY2Q5YTYwMzYyY2I4NCIsImlhdCI6MTcxODE1NTE5MywiZXhwIjoxNzE4MzI3OTkzfQ.P0ReVWSz92glvopsXR93JLZNwJQ8FjPuXdrxkQk2Pck

###

## Обновить информацию о предложении

PATCH   http://localhost:1337/offers/6668d7b84dd596d36a2104ad HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG53aWNrQGdtYWlsLmNvbSIsIm5hbWUiOiJKb2huIFdpY2siLCJpZCI6IjY2NjhlZTczOWMwY2Q5YTYwMzYyY2I4NCIsImlhdCI6MTcxODE1NTE5MywiZXhwIjoxNzE4MzI3OTkzfQ.P0ReVWSz92glvopsXR93JLZNwJQ8FjPuXdrxkQk2Pck

{
  "rentCost": 77777
}

###

## Удалить предложение

DELETE  http://localhost:1337/offers/6668d7b84dd596d36a2104ad HTTP/1.1
Content-Type: application/json

###

## Создание комментария к объявлению
POST http://localhost:1337/offers/6668d7b84dd596d36a2104ad/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG53aWNrQGdtYWlsLmNvbSIsIm5hbWUiOiJKb2huIFdpY2siLCJpZCI6IjY2NjhlZTczOWMwY2Q5YTYwMzYyY2I4NCIsImlhdCI6MTcxODE1NTE5MywiZXhwIjoxNzE4MzI3OTkzfQ.P0ReVWSz92glvopsXR93JLZNwJQ8FjPuXdrxkQk2Pck

{
   "text": "Супер!",
   "rating": 5
}

###

## Получение комментариев к объявлению
GET http://localhost:1337/offers/6668d7b84dd596d36a2104ad/comments HTTP/1.1
Content-Type: application/json

###
